# Generated by Django 2.2 on 2023-11-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ghghj', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
